theme: jekyll-theme-minimal
logo: '/Notebooks/PhDRepoCover.png
title: EastBIO PhD Project
description: Identifying Engineering Candidates for Advanced Biocatalysis in Biofuel Production
author: Emma E. M. Hobbs
