theme: jekyll-theme-minimal
logo: '/assets/repophdcover.pn'
title: EastBIO PhD Project
description: Repository containing pyrewton program and documentation written to identify engineering candidates for advanced biocatalysis in biofuel production
