title: EastBIO PhD Project: Engineering Plant Cell Wall Degrading Enzymes for Enhanced Biocatalysts in Biofuel Production
author: Emma E. M. Hobbs
description: > Repositroy containing all Python scripts used to identify and characterise candidates for engineering for enhanced biocatakyst in biofuel production.
theme: jekyll-theme-minimal
