coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: true
    patch: true
    changes: false

comment:
  layout: "header, diff"
  behavior: default
 
 token: 6ff3cc1b-5e92-4dd8-9d21-7b5ca9521730
