version: 2.1

orbs:
  codecov: codecov/codecov@1.0.5

jobs:
  build-and-test:
    docker:
      - image: circleci/python:3.7.5

    working_directory: ~/phd_eastbio

    steps:
      - checkout

      - restore_cache:
          keys:
            - phd_eastbio_standrews-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - phd_eastbio_standrews-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: phd_eastbio_standrews-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install package
          command: |
            . venv/bin/activate
            pip install -e .

      - run:
          name: test
          command: |
            . venv/bin/activate
            pytest -v
      
      - store_artifacts:
          path: tests/test_output
          destination: tests/test_output
      - store_artifacts:
          path: .coverage.xml
          destination: .coverage.xml
          
      - codecov/upload:
          file: .coverage.xml

workflows:
  main:
    jobs:
      - build-and-test
